#lang racket

(provide (all-defined-out))

(define (pretty-print program)
  (define (space-separate el)
    (printf " ~a" el))
  (define (print-block block)
    (if (equal? (car block) `read) (print-read-block block) (print-base-block block))
    (printf "\n"))
  (define (print-read-block block)
    (printf "read")
    (map space-separate (cdr block))
    (printf "\n"))
  (define (print-base-block block)
    (define (print-statement statement)
      (printf "    ")
      (if (equal? (car statement) `:=) (print-assign statement) (print-not-assign statement)))
    (define (print-assign statement)
      (printf "~a := ~a\n" (cadr statement) (caddr statement)))
    (define (print-not-assign statement)
      (printf "~a" (car statement))
      (map space-separate (cdr statement))
      (printf "\n"))
    (printf "~a:\n" (car block))
    (map print-statement (cdr block)))
  (map print-block (relabel-program program))
  (void))

(define (relabel-program program)
  (define duplicate-cnt (make-hash))
  (define new-labels (make-hash))

  (define (relabel label)
    (when (not (hash-has-key? new-labels label))
      (let()
          (define orig-label (car label))
          (if (hash-has-key? duplicate-cnt orig-label)
              (dict-set! duplicate-cnt orig-label (+ (dict-ref duplicate-cnt orig-label) 1))
              (dict-set! duplicate-cnt orig-label 0))
          (define duplicates (dict-ref duplicate-cnt orig-label))
          (dict-set! new-labels label (string-append (~a orig-label) "_" (~a duplicates)))))
    (dict-ref new-labels label))

  (define (relabel-block bb)
    (cons (relabel (car bb))
          (for/list ([command (cdr bb)])
            (match command
              [`(if ,expr goto ,then goto ,else) `(if ,expr goto ,(relabel then) goto  ,(relabel else))]
              [`(goto ,label) `(goto ,(relabel label))]
              [_ command]))))

  (cons (car program)
        (for/list ([bb (cdr program)])
          (relabel-block bb))))